### ISSUE TITLE
New Development

### ISSUE THREAD

**Issue by Galixte** [david63/breadcrumbmenu#1]
Hi @david63,

did you start from the Sajaki version available here: https://github.com/Sajaki/BreadcrumbMenu/tree/develop32?

Because I noted this information is different: https://github.com/Sajaki/BreadcrumbMenu/blob/develop32/styles/all/template/event/overall_footer_after.html#L10 Sajaki used the 1.12.1 version while you use the 1.11.2 version of jquery-ui-1.xx.x.custom.min.js like 1.0.6 version from this extension: https://github.com/david63/breadcrumbmenu/blob/master/styles/all/template/event/overall_footer_after.html#L10.

is it intended?

An other difference between Sajaki version: https://github.com/Sajaki/BreadcrumbMenu/blob/develop32/event/listener.php#L118 and yours: https://github.com/david63/breadcrumbmenu/blob/master/event/listener.php#L118.

Regards.

**Comment by david63** [comment]
All I did was take PayBas's extension and make it compatible with 3.2 and added an event so that other extensions could hook into it - which is how it should have been in the first place and not have "hard coded" extensions added.

**Comment by Galixte** [comment]
OK, fixed here: https://github.com/david63/breadcrumbmenu/commit/601eb16aa68d1886ad7435de5996a2bf0bd75fa5#diff-66a4b54be1550a6a8db4d8ff46bdc2e54ebbed6c0ff580b883e30f62476bf909, thanks!
