### ISSUE TITLE
PHP Warning: in file paybas/breadcrumbmenu/event/listener.php on line 208: Undefined array key -1

### ISSUE THREAD

**Issue by andreaskou** [david63/breadcrumbmenu#2]
`[phpBB Debug] PHP Warning: in file [ROOT]/ext/paybas/breadcrumbmenu/event/listener.php on line 208: Undefined array key -1
[phpBB Debug] PHP Warning: in file [ROOT]/ext/paybas/breadcrumbmenu/event/listener.php on line 208: Trying to access array offset on value of type null`

When you are in pm->sent->[any sent pm]

Using phpbb : 3.3.5
php : 8.0.15

All the best!

**Comment by david63** [comment]
Can you try changing line 203 of the listener  to `if ($current_id < 1 || empty($list))`

That seems to fix it on my test board but not sure if there may be other issues

**Comment by andreaskou** [comment]
Hello, yes it seems to be working.
I got no error messages.
